// <auto-generated />
namespace Nottit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AllInitialEntities : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207141416454_AllInitialEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1a227jNhB9L9B/EPTUFlgrSYHFbmDvInWSIujmgjjZ1wUjjR1iKVIlqdT+tj70k/oLJXWlREmW4+sW+2aTnOHcODM81L9//zP8OA+J8wJcYEZH7vHgyHWA+izAdDZyYzl98879+OHHH4YXQTh3PufrTvQ6RUnFyH2WMjr1POE/Q4jEIMQ+Z4JN5cBnoYcC5p0cHb3zjo88UCxcxctxhvcxlTiE5I/6O2bUh0jGiFyzAIjIxtXMJOHq3KAQRIR8GLk3TEosB+lC1zkjGCkhJkCmK0p09F5L5BZ7qd0ulFRy8bCIINlx5D4K4OYKteYPWFQG1NAdZxFwubiHaUZ3FbiOV6Xz6oQFmUGjt1a/qPz1xHVuYkLQE1EDU0QEuE709nQiGYffgQJHEoI7JCVwqmkhET0zwWn0tp8V3ntHJ9oKHqKUSSSVcy3Ba2Jqk+hfubATyVWsuM4lnkPwCehMPhcCX6N5PqJ+us4jxSq0FJHkMZgKpv+7N75DQvzFeLD9jW/QC54lxqiJMGZhqAytwu4eSLJAPOMojb5BNvnlLJbPjCu5OAvvGSnJspkvD4jPQCo1WOP0hMXcX0GoT5h+bZZIzzSIYwxbsphzTYIMvfKMdJ6cTKnvh8fy1XJRu3mk3lmXywPM5R5PkjZEe8yW56wWtflEc9wWs6seofyMrHOq8z1bTnUu8KsOU2Kt7ydpC6cAS7L7SvbIyR6PXkew9ygY9TBvKiYbKac9E0GjPFaa6HPqzoRgPk7EMI5dbo6qShc0cDpsk7o210J5MiYSRwT7atuR+4tloWZ2RY4r2SX9aI3dsVtPBLf0HAhIcM58mbTrYyR8FNgxoiwRVEdU7gCuDzEiqikXkiNMpZ1oMPVxhEi70DWSntlJi1Qwr8+cQwRUJ5h2y/fZtUwc9t7FFjUzLbPK0DOCp0dMFWHdGQZ2jHfH1UYDoU2WhqDMW72lYf764KqbYlfhVVe7z755j7eX8Kq1"
                       + "K20+betdXuHUVqbfTPpqlnsHIdbshYNLYmm5VDRSUQDPREhxmPMnK8b04glIAy5Q5bssuZVQsGKpSlyWf4u+iM8lLLLbsUWfJtAasWGAKoeiKTJWNPRMdV90twmFqIWUljO7GwODQWbm+gGpKtRX2dLsLeo2168eFWx1la3CY7Ao5Vxb7/o1z1a8K7P2ya095O6TTdfwed74Fie5hFm9FGfN8VivBZAdXqMoUvcVA6DNRpxJis6O30xWh2HDlIfniwY0tpC22EndPdEMarPaYAFcYi7kOZLoCekb1DgIrWXL8la+jZm+bC/l2SRfrX+beTHDpwc2gGxa7VIpop2c6AQ119pkCR6OCOINV/YxI3FI28tSO3UJ6Jo8ytH+nEqE1uRUjtqchl7NElY1s0xttQBVv/Xyakf+6uvYRnyzl29bKbfj3rwdNTm0tajtXMqGw+TT3oa0c0qBR5NLOnIwwZEWptdHhg3W9QqLZrLtxMQGvZkCaBV3pkMrJCANh1Vyjx7YcTxYxbG+pNi9KJK1YjjMCtPyJ0yrUqVLXEcZ5gUHukpNFkJCONALBpM/yZjgpNnNF1wjiqcg5AP7Cvo5VhXS1z+FFuirEAE5xPdQrFVfCjmvCP3W3zHpC+L+M+I/hWj+87pvkyswO/wXta2Yv/oSlmyx5jvYa3iYr2Db8Nl+Hm624rCNmNt8blnrwBlPKBvw2zow7b5g2QIA2SkSu0NY7H8DtqZQ1y5h0H1GScuNd69RcghvPgccJL3S2DcWHr2T1QFA6TZytRxTb4XU07vEyA2emPJpWgmbkcIWtL0LbG9i3orCNkHxrUh8E+dGiHgHuLWFU/cBapsQ3sMCps2wKVHG/am2kYeV1ZXq5eHNwOg2IqByh/Hps8paAs9KFvpDaAp+JWsUa67olOXpqyZRvqTWJF+DRIFKKWdc4inypZr2QYjkg6PPiMRqyUX4BMEVvY1lFEulMoRPZGEaQyfBrv2Tt4KqzMPbKPmW"
                       + "ZxMqKDGxUgFu6W8xJkEh96V93WhjobNrdg/SvpT6PjRbFJxuGO3JKDNfURQeIIyIYiZu6QS9QLtsy21YtdjwHKMZR6HIeJT06q8KvyCcf/gP3Y2jZrwvAAA="; }
        }
    }
}
