// <auto-generated />
namespace Nottit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class addLinkVote : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207150327041_addLinkVote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1c227cNhB9L9B/EPTUFsjKcYEgCXYTuGu7CBrbgdfOq0FL3DURilQlrrv7bX3oJ/UXSupK8aKl9u4ibzYvwxnOmYs4Y//79z/Dj4sYe88wzRAlI//14MT3IAlphMhs5M/Z9NVb/+OHH38YXkTxwvtarTsV6/hOko38J8aS90GQhU8wBtkgRmFKMzplg5DGAYhocHpy8jZ4fRJATsLntDxveDsnDMUw/4X/OqYkhAmbA3xFI4izcpzPTHKq3jWIYZaAEI78a8oYYoNioe+dYQQ4ExOIpz05OnknOPLrs/hpF5wrtrxbJjA/ceTfZzCVV/A1f8Bla4APfUlpAlO2vIXTct+nyPeC9r5A3Vhvk/aIo/lPhP166nvXc4zBI+YDU4Az6HvJm/cTRlP4OyQwBQxGXwBjMCViL8xZL6/gffLG7RbeBSen4hYCQAhlgHHlaowrbIorET9VzE5YyrHie5doAaPPkMzYU83wFVhUI/xH37sniEOLb2LpHMoCFr93H/wFZNlfNI12f/A1eEaz/DIUFsY0jvlFc9jdQpwvyJ5QUqBvUE4+nM3ZE005XymNbylutpUzD3cgnUHGxaDG6Qmdp2EPpj4j8s3MkZgxsCMNa7zIcyZGhkFjI52WUwr13Xg0Xa1mtZtGoZ1NqdzBBTugJYmLsGO2sTMFtdWEGbf1bF8TqmxkE6uuzrRYdcXwWsaU39Z3S9qBFSCG9x/J7lN8QNPrALtDwFBhbgomWwmnjo7AyI/mJlw5+koZtLMjZh8Kz9Vmp54w+qVmdqOIWpH67gjaKgN4DjfzAuJWN3Yla4X2TiDabTRHVLnEgMR8xmgZ0nRf0+iM2A6WYWWnZTculnGWZTREORsSb5XfaotzQSKvw4kVPriSgrvcOWYowSjkx478X7TbMZOrjb4hl384KuRe+6qh3pBziCGD3lnI8u/qMchCEOk44TcRtUe4bcNUGBnA/Os5YylAhOmOAJEQJQDb"
                       + "mVa2OHoPwVJNXJ05hwkkwgHYb97l1CbC62fXRyjXtOpWhoEEHgdM1fGnEwZ6MOrG1VaBYOPFAMrqm2wlzNcHl3oV+4KXKrbLuZXHPhi8JDfepVOTT28DLE8LejovQyh4Ef5L53tPGNPV4HJwnVscFmWGL0gDHNqBeksYa+fFe/SMm0FMZnufCJN1cPReTHkdsWHB9lSyRmiyEn0xTszM9x4gZtbC0aViRdLP9zC+A6YlC0XZ5/xRw5hYPIFMqk7wD/jmw6EFBQ1L7c3Na4O2v8bnChLlY7y2v3B2DpvLFwgjgcIFK0SkW2xTqh9ypBWGdx5Vod1fTDXLtagaIrq/kSQCpa5UK2sL5CpsozuLuOZU3iGZ7y+yloNLJBo+tyK3/BJgFtyWZLqkmYroJTZXiG9ILHekdOnVoUN2PfVxSH7Wl7yV7qzCzhqCqwUJXfKuoOwSlh3Q6hKIN1B69fJTB4F6bhgUHQHlwDCwtA4Mr0CSIDKTWgnKEW9S9BGMX036NwzEBY0gzAx9AzW39UmMpmAGlVlxYRG8RGnGzgEDj0C8C46jWFu2KuRVx8iRT9dSFUeq1eJnOaSWnRQDvdVBvrVLLohQci4TVFSrb/NE5wbAIDW8KY8pnsfEntHYdzetBzKNZtSdUtNLIFNqRnVKw0C5CS0R0q5ayx7benPSakfUclWssRLvpFvrzt2ot/qSkSnYvm7sVJpcVaZjz2DtlIoSuUylGDkacBQhZX1kmCKjAyzM23aDiS1qsyj1ttRZDPVwQKJw2/I9YuCo8FBkKpthQq8yOuPCvHU32CgrfzKBcqgHjep5rkXF9mZnp9PPd+0UH1rypC6pT6+TKCVZGpaJy+pmTC2TKZb4Hr+eZxSJLGayzBiMB2LBYPInHmOUf0dXC64AQVOYsTv6DYrGUp5ord/UWZePsyzCx9jZiYToK2vmPSvPakcmeQZp+ATSn2Kw+HnTLssexI6/N3An198u/OdHbNjRtw4NuZ9v"
                       + "Fzo7TAvaThS2leuWG8c2MjipGWxXejtM19BOdNfq9llHcUqvzzok+hp8zz4Wp56DQ/UY1O/ge20r2GN15H9TcysqHvushh0SJZbXq4Oi5BgamI4YJE5u7IXBw9lZHQE2HLqPDg2PouC5ViPK0cPE8sjycjuIDtn2uG+g7Csp6QWUPWYl5h4Nva5lebaU32BsvRrFS9LIjx4p12yRXJvriJY2jq4uDhNxa2Xe1KZhbfEwUTaXfm3dH53NHzbyxgL1HtoltBK3S6XYVGI+rsq4jMymzHk40bbSz9NfKCcNH7ZzZT2hZDtr1y6OrDOln31tS7Qe/Rd6qYCHFem/O/CQlqFZQ0L8rwcCw1ZAqdd8IlNaxTWFo2qJ8hZzBRmIeLQ5SxmagpDx6RBmWf43lflb0ci/iB9h9InczFkyZ1xkGD/ipXwZIj52nZ83mbR5Ht4k+V9BbUMEzibiIsAb8tsc4ajm+9LwkmQhIQJv+cgmdMnEY9tsWVO6psSRUHl9db5wB+MEc2LZDZmAZ2jnbfUdtm9seI7ALAVxVtJo9vNfOfyiePHhP1kNRXmfRAAA"; }
        }
    }
}
